Traceback (most recent call last):
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import xarray as xr 
import intake
url = 'https://raw.githubusercontent.com/hytest-org/hytest/main/dataset_catalog/hytest_intake_catalog.yml'
cat = intake.open_catalog(url)
sampleData = cat['rechunking-tutorial-osn'].to_dask()
sampleData
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNoSuchBucket[0m                              Traceback (most recent call last)
File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:112[0m, in [0;36m_error_wrapper[0;34m(func, args, kwargs, retries)[0m
[1;32m    111[0m [38;5;28;01mtry[39;00m:
[0;32m--> 112[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    113[0m [38;5;28;01mexcept[39;00m S3_RETRYABLE_ERRORS [38;5;28;01mas[39;00m e:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/aiobotocore/client.py:358[0m, in [0;36mAioBaseClient._make_api_call[0;34m(self, operation_name, api_params)[0m
[1;32m    357[0m     error_class [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mexceptions[38;5;241m.[39mfrom_code(error_code)
[0;32m--> 358[0m     [38;5;28;01mraise[39;00m error_class(parsed_response, operation_name)
[1;32m    359[0m [38;5;28;01melse[39;00m:

[0;31mNoSuchBucket[0m: An error occurred (NoSuchBucket) when calling the GetObject operation: Unknown

The above exception was the direct cause of the following exception:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/mapping.py:143[0m, in [0;36mFSMap.__getitem__[0;34m(self, key, default)[0m
[1;32m    142[0m [38;5;28;01mtry[39;00m:
[0;32m--> 143[0m     result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfs[49m[38;5;241;43m.[39;49m[43mcat[49m[43m([49m[43mk[49m[43m)[49m
[1;32m    144[0m [38;5;28;01mexcept[39;00m [38;5;28mself[39m[38;5;241m.[39mmissing_exceptions:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/asyn.py:113[0m, in [0;36msync_wrapper.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    112[0m [38;5;28mself[39m [38;5;241m=[39m obj [38;5;129;01mor[39;00m args[[38;5;241m0[39m]
[0;32m--> 113[0m [38;5;28;01mreturn[39;00m [43msync[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloop[49m[43m,[49m[43m [49m[43mfunc[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/asyn.py:98[0m, in [0;36msync[0;34m(loop, func, timeout, *args, **kwargs)[0m
[1;32m     97[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(return_result, [38;5;167;01mBaseException[39;00m):
[0;32m---> 98[0m     [38;5;28;01mraise[39;00m return_result
[1;32m     99[0m [38;5;28;01melse[39;00m:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/asyn.py:53[0m, in [0;36m_runner[0;34m(event, coro, result, timeout)[0m
[1;32m     52[0m [38;5;28;01mtry[39;00m:
[0;32m---> 53[0m     result[[38;5;241m0[39m] [38;5;241m=[39m [38;5;28;01mawait[39;00m coro
[1;32m     54[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m ex:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/asyn.py:429[0m, in [0;36mAsyncFileSystem._cat[0;34m(self, path, recursive, on_error, batch_size, **kwargs)[0m
[1;32m    428[0m     [38;5;28;01mif[39;00m ex:
[0;32m--> 429[0m         [38;5;28;01mraise[39;00m ex
[1;32m    430[0m [38;5;28;01mif[39;00m (
[1;32m    431[0m     [38;5;28mlen[39m(paths) [38;5;241m>[39m [38;5;241m1[39m
[1;32m    432[0m     [38;5;129;01mor[39;00m [38;5;28misinstance[39m(path, [38;5;28mlist[39m)
[1;32m    433[0m     [38;5;129;01mor[39;00m paths[[38;5;241m0[39m] [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39m_strip_protocol(path)
[1;32m    434[0m ):

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/asyncio/tasks.py:452[0m, in [0;36mwait_for[0;34m(fut, timeout)[0m
[1;32m    451[0m [38;5;28;01mif[39;00m timeout [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 452[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m fut
[1;32m    454[0m [38;5;28;01mif[39;00m timeout [38;5;241m<[39m[38;5;241m=[39m [38;5;241m0[39m:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:1013[0m, in [0;36mS3FileSystem._cat_file[0;34m(self, path, version_id, start, end)[0m
[1;32m   1011[0m         resp[[38;5;124m"[39m[38;5;124mBody[39m[38;5;124m"[39m][38;5;241m.[39mclose()
[0;32m-> 1013[0m [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m _error_wrapper(_call_and_read, retries[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mretries)

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:139[0m, in [0;36m_error_wrapper[0;34m(func, args, kwargs, retries)[0m
[1;32m    138[0m err [38;5;241m=[39m translate_boto_error(err)
[0;32m--> 139[0m [38;5;28;01mraise[39;00m err

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:112[0m, in [0;36m_error_wrapper[0;34m(func, args, kwargs, retries)[0m
[1;32m    111[0m [38;5;28;01mtry[39;00m:
[0;32m--> 112[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    113[0m [38;5;28;01mexcept[39;00m S3_RETRYABLE_ERRORS [38;5;28;01mas[39;00m e:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:1000[0m, in [0;36mS3FileSystem._cat_file.<locals>._call_and_read[0;34m()[0m
[1;32m    999[0m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m [38;5;21m_call_and_read[39m():
[0;32m-> 1000[0m     resp [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_call_s3(
[1;32m   1001[0m         [38;5;124m"[39m[38;5;124mget_object[39m[38;5;124m"[39m,
[1;32m   1002[0m         Bucket[38;5;241m=[39mbucket,
[1;32m   1003[0m         Key[38;5;241m=[39mkey,
[1;32m   1004[0m         [38;5;241m*[39m[38;5;241m*[39mversion_id_kw(version_id [38;5;129;01mor[39;00m vers),
[1;32m   1005[0m         [38;5;241m*[39m[38;5;241m*[39mhead,
[1;32m   1006[0m         [38;5;241m*[39m[38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mreq_kw,
[1;32m   1007[0m     )
[1;32m   1008[0m     [38;5;28;01mtry[39;00m:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:339[0m, in [0;36mS3FileSystem._call_s3[0;34m(self, method, *akwarglist, **kwargs)[0m
[1;32m    338[0m additional_kwargs [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_s3_method_kwargs(method, [38;5;241m*[39makwarglist, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 339[0m [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m _error_wrapper(
[1;32m    340[0m     method, kwargs[38;5;241m=[39madditional_kwargs, retries[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mretries
[1;32m    341[0m )

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/s3fs/core.py:139[0m, in [0;36m_error_wrapper[0;34m(func, args, kwargs, retries)[0m
[1;32m    138[0m err [38;5;241m=[39m translate_boto_error(err)
[0;32m--> 139[0m [38;5;28;01mraise[39;00m err

[0;31mFileNotFoundError[0m: An error occurred (NoSuchBucket) when calling the GetObject operation: Unknown

During handling of the above exception, another exception occurred:

[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/zarr/storage.py:1428[0m, in [0;36mFSStore.__getitem__[0;34m(self, key)[0m
[1;32m   1427[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1428[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmap[49m[43m[[49m[43mkey[49m[43m][49m
[1;32m   1429[0m [38;5;28;01mexcept[39;00m [38;5;28mself[39m[38;5;241m.[39mexceptions [38;5;28;01mas[39;00m e:

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/fsspec/mapping.py:147[0m, in [0;36mFSMap.__getitem__[0;34m(self, key, default)[0m
[1;32m    146[0m         [38;5;28;01mreturn[39;00m default
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key)
[1;32m    148[0m [38;5;28;01mreturn[39;00m result

[0;31mKeyError[0m: '.zmetadata'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      3[0m url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://raw.githubusercontent.com/hytest-org/hytest/main/dataset_catalog/hytest_intake_catalog.yml[39m[38;5;124m'[39m
[1;32m      4[0m cat [38;5;241m=[39m intake[38;5;241m.[39mopen_catalog(url)
[0;32m----> 5[0m sampleData [38;5;241m=[39m [43mcat[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mrechunking-tutorial-osn[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241;43m.[39;49m[43mto_dask[49m[43m([49m[43m)[49m
[1;32m      6[0m sampleData

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/intake_xarray/base.py:69[0m, in [0;36mDataSourceMixin.to_dask[0;34m(self)[0m
[1;32m     67[0m [38;5;28;01mdef[39;00m [38;5;21mto_dask[39m([38;5;28mself[39m):
[1;32m     68[0m [38;5;250m    [39m[38;5;124;03m"""Return xarray object where variables are dask arrays"""[39;00m
[0;32m---> 69[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mread_chunked[49m[43m([49m[43m)[49m

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/intake_xarray/base.py:44[0m, in [0;36mDataSourceMixin.read_chunked[0;34m(self)[0m
[1;32m     42[0m [38;5;28;01mdef[39;00m [38;5;21mread_chunked[39m([38;5;28mself[39m):
[1;32m     43[0m [38;5;250m    [39m[38;5;124;03m"""Return xarray object (which will have chunks)"""[39;00m
[0;32m---> 44[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_load_metadata[49m[43m([49m[43m)[49m
[1;32m     45[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_ds

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/intake/source/base.py:283[0m, in [0;36mDataSourceBase._load_metadata[0;34m(self)[0m
[1;32m    281[0m [38;5;250m[39m[38;5;124;03m"""load metadata only if needed"""[39;00m
[1;32m    282[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_schema [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 283[0m     [38;5;28mself[39m[38;5;241m.[39m_schema [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_schema[49m[43m([49m[43m)[49m
[1;32m    284[0m     [38;5;28mself[39m[38;5;241m.[39mdtype [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_schema[38;5;241m.[39mdtype
[1;32m    285[0m     [38;5;28mself[39m[38;5;241m.[39mshape [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_schema[38;5;241m.[39mshape

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/intake_xarray/base.py:18[0m, in [0;36mDataSourceMixin._get_schema[0;34m(self)[0m
[1;32m     15[0m [38;5;28mself[39m[38;5;241m.[39murlpath [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_cache([38;5;28mself[39m[38;5;241m.[39murlpath)[[38;5;241m0[39m]
[1;32m     17[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_ds [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 18[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open_dataset[49m[43m([49m[43m)[49m
[1;32m     20[0m     metadata [38;5;241m=[39m {
[1;32m     21[0m         [38;5;124m'[39m[38;5;124mdims[39m[38;5;124m'[39m: [38;5;28mdict[39m([38;5;28mself[39m[38;5;241m.[39m_ds[38;5;241m.[39mdims),
[1;32m     22[0m         [38;5;124m'[39m[38;5;124mdata_vars[39m[38;5;124m'[39m: {k: [38;5;28mlist[39m([38;5;28mself[39m[38;5;241m.[39m_ds[k][38;5;241m.[39mcoords)
[1;32m     23[0m                       [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_ds[38;5;241m.[39mdata_vars[38;5;241m.[39mkeys()},
[1;32m     24[0m         [38;5;124m'[39m[38;5;124mcoords[39m[38;5;124m'[39m: [38;5;28mtuple[39m([38;5;28mself[39m[38;5;241m.[39m_ds[38;5;241m.[39mcoords[38;5;241m.[39mkeys()),
[1;32m     25[0m     }
[1;32m     26[0m     [38;5;28;01mif[39;00m [38;5;28mgetattr[39m([38;5;28mself[39m, [38;5;124m'[39m[38;5;124mon_server[39m[38;5;124m'[39m, [38;5;28;01mFalse[39;00m):

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/intake_xarray/xzarr.py:46[0m, in [0;36mZarrSource._open_dataset[0;34m(self)[0m
[1;32m     44[0m     [38;5;28mself[39m[38;5;241m.[39m_ds [38;5;241m=[39m xr[38;5;241m.[39mopen_mfdataset([38;5;28mself[39m[38;5;241m.[39murlpath, [38;5;241m*[39m[38;5;241m*[39mkw)
[1;32m     45[0m [38;5;28;01melse[39;00m:
[0;32m---> 46[0m     [38;5;28mself[39m[38;5;241m.[39m_ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43murlpath[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkw[49m[43m)[49m

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/xarray/backends/api.py:572[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[0m
[1;32m    560[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    561[0m     decode_cf,
[1;32m    562[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    568[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    569[0m )
[1;32m    571[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 572[0m backend_ds [38;5;241m=[39m [43mbackend[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m    573[0m [43m    [49m[43mfilename_or_obj[49m[43m,[49m
[1;32m    574[0m [43m    [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m    575[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mdecoders[49m[43m,[49m
[1;32m    576[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    577[0m [43m[49m[43m)[49m
[1;32m    578[0m ds [38;5;241m=[39m _dataset_from_backend_dataset(
[1;32m    579[0m     backend_ds,
[1;32m    580[0m     filename_or_obj,
[0;32m   (...)[0m
[1;32m    590[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    591[0m )
[1;32m    592[0m [38;5;28;01mreturn[39;00m ds

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/xarray/backends/zarr.py:1011[0m, in [0;36mZarrBackendEntrypoint.open_dataset[0;34m(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, synchronizer, consolidated, chunk_store, storage_options, stacklevel, zarr_version)[0m
[1;32m    990[0m [38;5;28;01mdef[39;00m [38;5;21mopen_dataset[39m(  [38;5;66;03m# type: ignore[override]  # allow LSP violation, not supporting **kwargs[39;00m
[1;32m    991[0m     [38;5;28mself[39m,
[1;32m    992[0m     filename_or_obj: [38;5;28mstr[39m [38;5;241m|[39m os[38;5;241m.[39mPathLike[Any] [38;5;241m|[39m BufferedIOBase [38;5;241m|[39m AbstractDataStore,
[0;32m   (...)[0m
[1;32m   1008[0m     zarr_version[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m   1009[0m ) [38;5;241m-[39m[38;5;241m>[39m Dataset:
[1;32m   1010[0m     filename_or_obj [38;5;241m=[39m _normalize_path(filename_or_obj)
[0;32m-> 1011[0m     store [38;5;241m=[39m [43mZarrStore[49m[38;5;241;43m.[39;49m[43mopen_group[49m[43m([49m
[1;32m   1012[0m [43m        [49m[43mfilename_or_obj[49m[43m,[49m
[1;32m   1013[0m [43m        [49m[43mgroup[49m[38;5;241;43m=[39;49m[43mgroup[49m[43m,[49m
[1;32m   1014[0m [43m        [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m,[49m
[1;32m   1015[0m [43m        [49m[43msynchronizer[49m[38;5;241;43m=[39;49m[43msynchronizer[49m[43m,[49m
[1;32m   1016[0m [43m        [49m[43mconsolidated[49m[38;5;241;43m=[39;49m[43mconsolidated[49m[43m,[49m
[1;32m   1017[0m [43m        [49m[43mconsolidate_on_close[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m   1018[0m [43m        [49m[43mchunk_store[49m[38;5;241;43m=[39;49m[43mchunk_store[49m[43m,[49m
[1;32m   1019[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[1;32m   1020[0m [43m        [49m[43mstacklevel[49m[38;5;241;43m=[39;49m[43mstacklevel[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;241;43m1[39;49m[43m,[49m
[1;32m   1021[0m [43m        [49m[43mzarr_version[49m[38;5;241;43m=[39;49m[43mzarr_version[49m[43m,[49m
[1;32m   1022[0m [43m    [49m[43m)[49m
[1;32m   1024[0m     store_entrypoint [38;5;241m=[39m StoreBackendEntrypoint()
[1;32m   1025[0m     [38;5;28;01mwith[39;00m close_on_error(store):

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/xarray/backends/zarr.py:464[0m, in [0;36mZarrStore.open_group[0;34m(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close, chunk_store, storage_options, append_dim, write_region, safe_chunks, stacklevel, zarr_version, write_empty)[0m
[1;32m    461[0m             [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such file or directory: [39m[38;5;124m'[39m[38;5;132;01m{[39;00mstore[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)
[1;32m    462[0m [38;5;28;01melif[39;00m consolidated:
[1;32m    463[0m     [38;5;66;03m# TODO: an option to pass the metadata_key keyword[39;00m
[0;32m--> 464[0m     zarr_group [38;5;241m=[39m [43mzarr[49m[38;5;241;43m.[39;49m[43mopen_consolidated[49m[43m([49m[43mstore[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mopen_kwargs[49m[43m)[49m
[1;32m    465[0m [38;5;28;01melse[39;00m:
[1;32m    466[0m     zarr_group [38;5;241m=[39m zarr[38;5;241m.[39mopen_group(store, [38;5;241m*[39m[38;5;241m*[39mopen_kwargs)

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/zarr/convenience.py:1351[0m, in [0;36mopen_consolidated[0;34m(store, metadata_key, mode, **kwargs)[0m
[1;32m   1348[0m         metadata_key [38;5;241m=[39m [38;5;124m"[39m[38;5;124mmeta/root/consolidated/[39m[38;5;124m"[39m [38;5;241m+[39m metadata_key
[1;32m   1350[0m [38;5;66;03m# setup metadata store[39;00m
[0;32m-> 1351[0m meta_store [38;5;241m=[39m [43mConsolidatedStoreClass[49m[43m([49m[43mstore[49m[43m,[49m[43m [49m[43mmetadata_key[49m[38;5;241;43m=[39;49m[43mmetadata_key[49m[43m)[49m
[1;32m   1353[0m [38;5;66;03m# pass through[39;00m
[1;32m   1354[0m chunk_store [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mchunk_store[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;129;01mor[39;00m store

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/zarr/storage.py:2947[0m, in [0;36mConsolidatedMetadataStore.__init__[0;34m(self, store, metadata_key)[0m
[1;32m   2944[0m [38;5;28mself[39m[38;5;241m.[39mstore [38;5;241m=[39m Store[38;5;241m.[39m_ensure_store(store)
[1;32m   2946[0m [38;5;66;03m# retrieve consolidated metadata[39;00m
[0;32m-> 2947[0m meta [38;5;241m=[39m json_loads([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstore[49m[43m[[49m[43mmetadata_key[49m[43m][49m)
[1;32m   2949[0m [38;5;66;03m# check format of consolidated metadata[39;00m
[1;32m   2950[0m consolidated_format [38;5;241m=[39m meta[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mzarr_consolidated_format[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)

File [0;32m/home/conda/global/9764ad0fe205ee3ccb00b4474c3e6708e73fb3a628843d562645d7d1e21ccb8d-20231221-205006-476455-52-pangeo/lib/python3.11/site-packages/zarr/storage.py:1430[0m, in [0;36mFSStore.__getitem__[0;34m(self, key)[0m
[1;32m   1428[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mmap[key]
[1;32m   1429[0m [38;5;28;01mexcept[39;00m [38;5;28mself[39m[38;5;241m.[39mexceptions [38;5;28;01mas[39;00m e:
[0;32m-> 1430[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m

[0;31mKeyError[0m: '.zmetadata'

